version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=payment_transactions_db
      - POSTGRES_USER=payment_admin
      - POSTGRES_PASSWORD=admin_pass
    ports:
      - 54321:5432
volumes:
  pgdata: