payments:
  retention:
    period: 1

jwt:
  issuer: PaymentsSystem
  secret: MIIBPQIBAAJBANkpF/lVw/COC3QGJmWfw5Kay97N7+O2LaKdo+eWuEFnCxGEiB67Q7/q7ntJeDg+vxMXK30w8w18e2Xjd9AqFY8CAwEAAQJBAII9RBSUnGwENNhD6/lc5QVi80xQBER0eVAi7S8y1JTb5Sqc/NPFT9KqeI8RpEv+uRx5K24hFzkkAFxRH2EggtkCIQD/hxD/7VrrRmWqAHicbmm9yvMktT53kCKNPspVbnUNewIhANmP3ocFpw4ghdN/tLgjQE1eCUIMhVvGicx9mK1WpFn9AiEAt0SMMMJv3ybSa6eC2c9nD7SrxrwnXWGHJn7OZ4+dbFkCIQCQeB+9q3w+Pkx/oHriF854Uax2Jphb1B/nIbPDzxf+BQIhAI5O3sI8LYKvBJhBTnzzWfjYQMaRmHMyz+0ZBbgfwXPq
  token_validity: 120

spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true
  application:
    name: Payment System POC
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PASS:admin_pass}
    url: ${DB_URL:jdbc:postgresql://localhost:54321/payment_transactions_db}
    username: ${DB_USER:payment_admin}
  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false